# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/opq20/LP_project/LP_project.srcs/sources_1/ip/hashtable/hashtable.xci
# IP: The module: 'hashtable' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/opq20/LP_project/LP_project.gen/sources_1/ip/hashtable/hashtable_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hashtable'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/opq20/LP_project/LP_project.srcs/sources_1/ip/hashtable/hashtable.xci
# IP: The module: 'hashtable' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/opq20/LP_project/LP_project.gen/sources_1/ip/hashtable/hashtable_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hashtable'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
